ontodeals/Dcupon/Dcupon/Controllers/CustomerController.cs
using Dcupon.DAL;
using Dcupon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Dcupon.Controllers
{
    public class CustomerController : Controller
    {

        private string Authentication { get; set; }
        private string Message { get; set; }
        // GET: Customer
        [HttpPost]
        public JsonResult Login(string email, string password)
        {
            CustomerDetails model = new CustomerDetails();
            model.Email = email;
            model.Password = password;
            CustomerDetails customerDetails = new CustomerDetails();
            Customer obj = new Customer();
            obj = customerDetails.ValidateUser(model);
            if (!string.IsNullOrEmpty(obj.Name))
            {
                Session["Username"] = obj.Name;
                return Json(new { Authentication = "Successfull", Message = "" });
            }
            else
            {
                Session["Loginstatus"] = false;
                return Json(new { Authentication = "UnSuccessfull", Message = "Incorrect Email/Password Combination" });
            }




        }

        public ActionResult DashBoard()
        {


            if (string.IsNullOrEmpty(Convert.ToString(Session["Username"])))
            {
                Session["Loginstatus"] = false;
                return RedirectToAction("index", "Home");

            }
            else
            {
                return View();
            }
        }

        public JsonResult Register(string name, string email, string password)
        {

            Customer model = new Customer();
            model.Name = name;
            model.Email = email;
            model.Password = password;
            CustomerDetails customerDetails = new CustomerDetails();

            if (customerDetails.CheckDuplicates(model.Email))
            {
                model.Password = Helper.Encrypt(model.Password, true);
                model.passwordVerificationToken = "";
                if (customerDetails.Save(model))
                {
                    Session["Username"] = model.Name;
                    return Json(new { Authentication = "Successfull", Message = "" });
                }
                else
                {
                    Session["Loginstatus"] = false;
                    return Json(new { Authentication = "UnSuccessfull", Message = "" });
                }
            }
            else
            {
                Session["Loginstatus"] = false;
                return Json(new { Authentication = "UnSuccessfull", Message = "Email Already Exsit" });

            }




        }

        public ActionResult GetRecharge(CustomerDetails model)
        {
            CustomerMobileModel customermob = new CustomerMobileModel();
            if (customermob.CheckDuplicatesMobile(model.custmobile.Mobile))
            {
                CustomerMobile obj = new CustomerMobile();
                obj.Name = model.custmobile.Name;
                obj.Mobile = model.custmobile.Mobile;
                obj.MobileOperator = model.custmobile.MobileOperator;
                obj.ConnectionType = model.custmobile.ConnectionType;
                if (customermob.Save(obj))
                {

                    return RedirectToAction("index", "Home");
                }
                else
                {

                    return RedirectToAction("index", "Home");
                }
            }
            else
            {
                return RedirectToAction("index", "Home");
            }
        }
        public ActionResult LogOut()
        {

            Session["Username"] = null;
            Session["Error"] = null;
            return RedirectToAction("index", "Home");

        }

        public JsonResult ForgotPassword(string email)
        {
            Customer model = new Customer();
            model.Email = email;

            CustomerDetails obj = new CustomerDetails();
            if (obj.ValidateUserEmail(model))
            {

                model = obj.Load(model);
                Email emailobj = new Email();
                var token = emailobj.GenerateToken();
                model.passwordVerificationToken = token;
                obj.Update(model);

                emailobj.PasswordResetEmail(email, token);

                return Json(new { Authentication = "Successfull", Message = "Email sent to the Registred Email-id" });
            }
            else
            {
                return Json(new { Authentication = "UnSuccessfull", Message = "Email-id does not exist" });
            }





        }

        [Route("PasswordReset")]
        public ActionResult PasswordReset(string email, string token)
        {
            CustomerDetails obj = new CustomerDetails();
            Customer model = new Customer();
            model.Email = email;
            model.passwordVerificationToken = token;
            if (obj.ValidateUserToken(model))
            {
                obj.Email = email;
                obj.passwordVerificationToken = token;
                return View(obj);

            }
            else
            {
                return RedirectToAction("index", "Home");

            }

        }




        public JsonResult UserPasswordReset(string email, string token, string newpassword)
        {
            CustomerDetails obj = new CustomerDetails();

            Customer model = new Customer();
            model.Email = email;
            model.passwordVerificationToken = token;
            if (obj.ValidateUserToken(model))
            {
                model = new Customer();
                model.Email = email;
                model = obj.Load(model);
                model.Password = Helper.Encrypt(newpassword, true);

                if (obj.Update(model))
                {
                    return Json(new { Authentication = "Successfull", Message = "Your Password has been reseted successfully" });
                }
                else
                {
                    return Json(new { Authentication = "UnSuccessfull", Message = "Email Not Validated" });
                }
            }

            else
            {
                return Json(new { Authentication = "UnSuccessfull", Message = "Error updating Password Please try later" });

            }

        }
    }
}

ontodeals/Dcupon/Dcupon/Controllers/HomeController.cs
using Dcupon.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
namespace Dcupon.Controllers
{



    public class HomeController : Controller
    {

        // GET: Home

        public ActionResult Index()
        {

            DataModel model = new DataModel();
            model.listofCupon = model.HomeDetails();
            model.listofdealsoftheday = model.LoadDealsofthedayCuponlist();
            model.listofTopOffers = model.LoadTopDealsofthedayCuponlist();
            model.listofsliders = model.LoadSliderlist();
            return View(model);

        }

        [Route("Coupons")]
        public ActionResult Coupons(string src, int? page)
        {
            DataModel model = new DataModel();
            model.listofCupon = model.LoadCuponlistbasedonwebtitle(src);
            ViewData["src"] = src;
            TempData["Page"] = "Coupons";
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(model.listofCupon.ToPagedList(pageNumber, pageSize));

        }

        [Route("SCoupons")]
        public ActionResult SCoupons(int src, int? page)
        {
            DataModel model = new DataModel();
            model.listofCupon = model.LoadCuponlistbasedonscategory(src);
            ViewData["src"] = src;
            TempData["Page"] = "Coupons";
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Coupons", model.listofCupon.ToPagedList(pageNumber, pageSize));

        }


        [Route("Categories")]
        public ActionResult Categories(string src, int? page)
        {
            DataModel model = new DataModel();
            model.listofCupon = model.LoadCuponlistbasedoncatergory(src);
            ViewData["src"] = src;
            TempData["Page"] = "Categories";
            WebsitesModel objcd = new WebsitesModel();
            model.listofwebsite = objcd.Load();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Coupons", model.listofCupon.ToPagedList(pageNumber, pageSize));

        }


        public ActionResult SearchList(string term)
        {
            string Searchtext = term;
            WebsitesModel Websitesdetails = new WebsitesModel();
            List<string> listofdetails = new List<string>();
            Websitesdetails.listWebsite = Websitesdetails.LoadSearchResults(Searchtext);
            listofdetails = (from ap in Websitesdetails.listWebsite
                             select (ap.Title)).ToList();
            return Json(listofdetails, JsonRequestBehavior.AllowGet);
        }

        [Route("Cupons")]
        public ActionResult Search(string search, int? page)
        {
            DataModel model = new DataModel();
            model.listofCupon = model.LoadCuponlistbasedonwebtitle(search);
            WebsitesModel objcd = new WebsitesModel();
            model.listofwebsite = objcd.Load();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View("Coupons", model.listofCupon.ToPagedList(pageNumber, pageSize));


        }


        public ActionResult _SideBar()
        {
            DataModel dt = new DataModel();
            WebsitesModel objcd = new WebsitesModel();
            dt.listofwebsite = objcd.LoadActive();
            return PartialView(dt);
        }
        public ActionResult LoadNavigationMenu()
        {
            DataModel dt = new DataModel();
            WebsitesModel objcd = new WebsitesModel();
            CatergoryModel objcm = new CatergoryModel();
            SubCategoryModel objscm = new SubCategoryModel();
            dt.listofCategory = objcm.LoadActive();
            dt.listofwebsite = objcd.LoadActive();
            dt.listofSubCategory = objscm.LoadActive();
            return PartialView("_NavigationPartial", dt);

        }


        public ActionResult _Register()
        {

            CustomerDetails model = new CustomerDetails();
            return PartialView("_Register", model);

        }


        [Route("about")]
        public ActionResult Aboutus()
        {

            return View();
        }
        [Route("contact")]
        public ActionResult Contactus()
        {

            return View();
        }
        [Route("privacypolicy")]
        public ActionResult privacypolicy()
        {

            return View();
        }
        [Route("termsofuse")]
        public ActionResult termsofuse()
        {

            return View();
        }
        [Route("sitemap")]
        public ActionResult sitemap()
        {

            return View();
        }
        [Route("faq")]
        public ActionResult faq()
        {

            return View();
        }
        [Route("press")]
        public ActionResult press()
        {

            return View();
        }
        [Route("whereismyrecharge")]
        public ActionResult whereismyrecharge()
        {

            return View();
        }

        [Route("rechargeoffers")]
        public ActionResult RechargeOffers()
        {

            return View();
        }

        [Route("howitworks")]
        public ActionResult howitworks()
        {

            return View();
        }
    }
}

ontodeals/Dcupon/Dcupon/Views/Home/Aboutus.cshtml
@{
    ViewBag.Title = "Aboutus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container text-block">
    <div class="col-md-12"><br /><br />
        <div class="new_title center">
            <h2>About Ontodeals</h2>
        </div> <br/>

        <p> We choose the Best deals Online and update them better than most other Coupon and Deal sites. </p>
        <p>
            Think of it as your personal “ONE STOP ONLINE SHOP” find the Best Price Right now and get assured  the biggest Online Savings possible on Shopping  | Fashion  | Electronics  | Travel   | Recharge | Food
            and on Top you will get Mobile Recharge or DTH Recharge or Gift Vouchers as Cash Back means, you’ll always save better shopping through Ontodeals.com,
        </p>
    
      <p>It’s like getting paid to shop online. Sign up for free or Enter your Mobile Number ,E-Mail i.d in Recharge Form and Shop , So you don’t miss any more Deals,Coupons or Savings.</p> 
           <br/><br /><br />
        

    </div>
</div>

ontodeals/Dcupon/Dcupon/Views/Home/Contactus.cshtml
@{
    ViewBag.Title = "Contactus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contactus</h2>

ontodeals/Dcupon/Dcupon/Views/Home/Coupons.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Dcupon.Models.DataModel>
 

    @{
        ViewBag.Title = "Coupons";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <section class="main-container col2-left-layout">
        <div class="main container">
            <div class="row">
                <section class="col-main col-sm-9 col-sm-push-3 animated">
                    @*<div class="category-title">
                        <h1>Tops &amp; Tees</h1>
                    </div>*@

                    <div class="category-products">
                        
                        <ol id="products-list" class="products-list">
                            
                            @for (int i = 0; i < Model.Count(); i++)
		  
                                  {
                                      if(i%2 !=0 || i==0)
                                      {  
                                    <li class="item odd">
                                        <div class="product-image"> <a target="_blank" href="@Model[i].RedirectUrl" title="@Model[i].Title"> <img class="small-image" src="@Model[i].ImageUrl" alt="" width="230"> </a> </div>
                                        <div class="product-shop">
                                            <h2 class="product-name"><a title=" Sample Product" target="_blank" href="@Model[i].RedirectUrl"> @Model[i].Title </a></h2>

                                            @*<div class="ratings">
                                                <div class="rating-box">
                                                    <div style="width:50%" class="rating"></div>
                                                </div>
                                                <p class="rating-links"> <a href="#">1 Review(s)</a> <span class="separator">|</span> <a href="#review-form">Add Your Review</a> </p>
                                            </div>*@
                                            <div class="desc std">
                                                <p>
                                                    @Model[i].Description
                                                </p>
                                                
                                            </div>
                                            <div class="actions">
                                                <a href="mailto:?subject=@Model[i].Title&amp;body=@Model[i].Description %20%20%0A%0AThanks%20fo%20choosing%20ontodeals.com">


                                                    <i class="fa fa-envelope" title="Mail this Coupon to Friends"></i>
                                                </a>
                                                <a href="@Model[i].RedirectUrl" class="coupon-popover" data-url="@Model[i].RedirectUrl"  data-cupon-type="@Model[i].RedirectType" data-cupon-code="@Model[i].CuponCode" data-coupon-description="@Model[i].Description" data-coupon-website="@Model[i].Website" target="_blank">View Deal </a>        
                                            </div>
                                    
                                      </div>
                                    
                                    </li>
                                      }

                                      else
                                      {

                                        <li class="item even">
                                            <div class="product-image"> <a href="@Model[i].RedirectUrl" title="Microsoft Natural Keyboard"> <img class="small-image" src="@Model[i].ImageUrl" alt="Microsoft Natural Keyboard" width="230"> </a> </div>
                                            <div class="product-shop">
                                                <h2 class="product-name"><a title=" Sample Product" href="product-detail.html"> @Model[i].Title  </a></h2>

                                                <div class="desc std">
                                                    <p>
                                                       @Model[i].Description 
                                                    
                                                    </p>
                                                </div>
                                                <div class="actions">
                                                    <a href="mailto:?subject=@Model[i].Title&amp;body=@Model[i].Description %20%20%0A%0AThanks%20fo%20choosing%20ontodeals.com">


                                                        <i class="fa fa-envelope" title="Mail this Coupon to Friends"></i>
                                                    </a>
                                                    <a href="@Model[i].RedirectUrl" class="coupon-popover" data-cupon-type="@Model[i].RedirectType" data-cupon-code="@Model[i].CuponCode" data-coupon-description="@Model[i].Description" data-coupon-website="@Model[i].Website" target="_blank">View Deal </a>        
                                                </div>

                                                </div>
                                        </li>
                                      }
                                   }
 
 
                           
                        </ol>
                    </div>

                    <div class="toolbar">

                        @*<div id="sort-by">
                <label class="left">Sort By: </label>
                <ul>
                    <li>
                        <a href="#">Position<span class="right-arrow"></span></a>
                        <ul>
                            <li><a href="#">Name</a></li>
                            <li><a href="#">Price</a></li>
                            <li><a href="#">Position</a></li>
                        </ul>
                    </li>
                </ul>
                <a class="button-asc left" href="#?dir=desc&amp;order=position" title="Set Descending Direction"><span style="color:#999;font-size:11px;" class="glyphicon glyphicon-arrow-up"></span></a>
            </div>*@
                        <div class="pager">

                            <div class="pages">
                                <label>Page:</label>
                                <ul class="pagination">
                                    @if (TempData["Page"] != null)
                                    {
                                        if (TempData["Page"] == "Coupons")
                                        {
                                            <li> @Html.PagedListPager(Model, page => Url.Action("Coupons", "Home", new { page, src = @ViewData["src"] }), new PagedListRenderOptions { LinkToFirstPageFormat = String.Format("<< First"), LinkToPreviousPageFormat = String.Format("<"), LinkToNextPageFormat = String.Format(">"), LinkToLastPageFormat = String.Format("Last >>"), MaximumPageNumbersToDisplay = 5 }) </li>
                                        }

                                        else
                                        {
                                            <li> @Html.PagedListPager(Model, page => Url.Action("Categories", "Home", new { page, src = @ViewData["src"] }), new PagedListRenderOptions { LinkToFirstPageFormat = String.Format("<< First"), LinkToPreviousPageFormat = String.Format("<"), LinkToNextPageFormat = String.Format(">"), LinkToLastPageFormat = String.Format("Last >>"), MaximumPageNumbersToDisplay = 5 }) </li>
                                        }
                                    }


                                </ul>
                            </div>
                        </div>
                    </div>

                </section>
               
                 @{Html.RenderAction("_SideBar", "Home");}
            </div>
        </div>
    </section>
  

ontodeals/Dcupon/Dcupon/Views/Home/_Register.cshtml
@model Dcupon.Models.CustomerDetails


<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id='myModal' tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-body clearfix">
                <div class="col-md-6 dark-bg-modal">
                    <p class="login-market">Welcome avail amazing discounts and offers</p>
                    @*<ul class="login-benefits">
                        <li><i class="fa fa-check"></i> Cashbacks and discounts on purchases</li>
                        <li><i class="fa fa-check"></i> Free Mobile Recharges for successful transaction</li>
                        <li><i class="fa fa-check"></i> Refer and earn special coupons</li>
                    </ul>*@

                </div>
                @using (Ajax.BeginForm("Login", "Customer", FormMethod.Post, new AjaxOptions { UpdateTargetId = "Productresults" }))
                {
                    <div class="col-md-6 user-form" id="Productresults">
                        
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                        <div class="alert alert-danger userError" role="alert">Invalid username or password.</div>

                        <div class="form-group">


                            <label>Email</label>

                            @Html.TextBoxFor(m => m.Email, new { @class = "validate[required] form-control", placeholder = "Enter your email address", required = "required" })

                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            
                            @Html.TextBoxFor(m => m.Password, new { @class = "validate[required] form-control", type = "password", placeholder = "********", required = "required" })

                        </div>

                        

                        <div class="form-group">
                            <button type="button" class="btn btn-primary pull-right userlogin">Login</button>
                            <a href="#" data-toggle="modal" data-target="#forgotpass" data-dismiss="modal" class="forgot-pass">Forgot Password? | </a>
                            <a href="#" data-toggle="modal" data-target="#userReg" data-dismiss="modal" class="new-user">New user?</a>
                        </div>



                    </div>
                }
            </div>

        </div>
    </div>
</div>
<!--modal-->
<!-- Modal -->
<div class="modal fade" id='userReg' tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-body clearfix">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                @using (Ajax.BeginForm("Register", "Customer", FormMethod.Post, new AjaxOptions { UpdateTargetId = "Productresult" }))
                {

                    <div class="col-md-10 user-reg-form" id="Productresult">


                        <div class="signup-header">
                            <p>Signup to earn mobile recharges and exlusive deals updates.</p>

                        </div>

                        <div class="alert alert-danger userError" role="alert">Invalid username or password.</div>

                        <div class="form-group">


                            <label>Name</label>


                            @Html.TextBoxFor(m => m.Name, new { @class = "validate[required] form-control", placeholder = "Enter your name", required = "required" })
                        </div>



                        <div class="form-group">


                            <label>Email</label>


                            @Html.TextBoxFor(m => m.Email, new { @class = "validate[required,custom[email]] form-control", placeholder = "Enter your email", required = "required" })
                        </div>

                  
                        <div class="form-group">
                            <label>Password</label>
                            @Html.TextBoxFor(m => m.Password, new { @class = "validate[required] form-control", type = "password", placeholder = "********", required = "required" })

                        </div>


                        <div class="form-group">
                            <input type="checkbox" checked="checked" disabled="disabled"/>
                            <span>By continuing, you agree to the <a href="@Url.Action("termsofuse","home")" class="termsofuse">Terms and Conditions.</a></span>

                        </div>
                        

                    

                        <div class="form-group">
                            <button type="button" class="btn btn-primary pull-right cust_login">Register</button>
                            <a href="#" data-toggle="modal" data-target="#myModal" data-dismiss="modal" class="new-user pull-right">Already registered?</a>
                        </div>

                    </div>
                }
            </div>

        </div>
    </div>
</div>
<!--modal-->

<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id='needrecharge' tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">

            <div class="modal-body clearfix">
                <div class="col-md-6 dark-bg-modal">
                    <p class="login-market">3 Easy Steps To Earn Recharge</p>
                    <ul class="login-benefits">
                        <li><i class="fa fa-check"></i> Enter your recharge details</li>
                        <li><i class="fa fa-check"></i> Visit store via <b>ontodeals</b></li>
                        <li><i class="fa fa-check"></i> Get recharge within 6 to 10 weeks</li>
                    </ul>

                </div>
                @using (Ajax.BeginForm("GetRecharge", "Customer", FormMethod.Post, new AjaxOptions { UpdateTargetId = "Getrecharge" }))
                {
                    <div class="col-md-6 user-form" id="Productresults">

                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                        <div class="form-group">


                            <label>Email</label>


                            @Html.TextBoxFor(m => m.custmobile.Name, new { @class = "form-control",  placeholder = "Enter your Email address", required = "required" })
                        </div>


                        <div class="form-group">


                            <label>Mobile</label>

                            @Html.TextBoxFor(m => m.custmobile.Mobile, new { @class = "form-control", id = "custmobile", placeholder = "Enter your mobile number", required = "required" })
                        </div>  

                        <div class="form-group">


                            <label>Mobile Operator</label>

                           
                            @Html.DropDownListFor(x => x.custmobile.MobileOperator, Model.MobileOperators, new { @class = "form-control", required = "required" })



                        </div>

                        <div class="form-group">
                            
                            
                            @Html.RadioButtonFor(x => x.custmobile.ConnectionType, new { @id = "1", name = "pre" })
                            <label>Prepaid</label>
                            @Html.RadioButtonFor(x => x.custmobile.ConnectionType, new { @id="2", name = "pre" })
                             
                            <label>Postpaid</label>

                        </div>
                       

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary pull-right">Yes i want free rechrage</button>
                            <a href="#" data-toggle="modal" data-dismiss="modal" aria-label="Close" class="new-user pull-right">skip</a>
                        </div>



                    </div>
                }
            </div>

        </div>
    </div>
</div>
<!--modal-->

@*<script>
    $(document).ready(function () {
      
        $('.cust_login').click(function () {

            var modelDataJSON =  '@Html.Raw(Json.Encode(Model))';
            //var obj=JSON.parse(modelDataJSON);
            //console.log(obj);

            $.ajax({
                url: "/Customer/Login",
                type: 'POST',
                dataType: 'json',
                data:  ,
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    alert(data);
                }
            });

        })



    })

</script>*@


<!-- Modal -->
<div class="modal fade" id='forgotpass' tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-body clearfix">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="alert alert-danger userError" role="alert"></div>
                <form>
                    <div class="form-group">


                        <label>Enter you registered Email id</label>
                        <input type="text" class="validate[required,custom[email]] form-control" id="forgotemail" />
                        <br />
                        <button type="button" class="btn btn-primary pull-right forgot-pass-submit">Submit</button>

                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<!--modal-->

ontodeals/Dcupon/Dcupon/Views/Home/press.cshtml
@{
    ViewBag.Title = "press";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>press</h2>

ontodeals/Dcupon/Dcupon/Views/Home/sitemap.cshtml
@{
    ViewBag.Title = "sitemap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>sitemap</h2>

ontodeals/Dcupon/Dcupon/Views/Home/whereismyrecharge.cshtml
@{
    ViewBag.Title = "whereismyrecharge";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>whereismyrecharge</h2>